services:
  uptime-kuma:
    image: louislam/uptime-kuma:2-slim
    restart: unless-stopped
    networks:
      - traefik_default
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.uptime.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.uptime.entrypoints=websecure
      - traefik.http.routers.uptime.tls=true
      - traefik.http.services.uptime.loadbalancer.server.port=3001
      - homepage.group=Infra
      - homepage.name=Uptime
      - homepage.href=https://${DOMAIN_NAME}
      - homepage.description=Uptime Monitor

networks:
  traefik_default:
    external: true
    name: traefik_default
