name: affine

services:
  affine:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine_server
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully

    networks:
      - traefik_default

    volumes:
      - Affine:/root/.affine/storage
      - /var/lib/affine/config:/root/.affine/config

    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://affine@postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false

    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.affine.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.affine.entrypoints=websecure
      - traefik.http.routers.affine.tls=true
      - traefik.http.services.affine.loadbalancer.server.port=3010
      - homepage.group=Utilities
      - homepage.name=Affine
      - homepage.href=https://${DOMAIN_NAME}
      - homepage.description=Knowledge Base

  affine_migration:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine_migration_job

    volumes:
      - Affine:/root/.affine/storage
      - /var/lib/affine/config:/root/.affine/config

    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']

    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://affine@postgres:5432/affine
      - AFFINE_INDEXER_ENABLED=false

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    container_name: affine_postgres

    volumes:
      - /var/lib/affine/postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: affine
      POSTGRES_DB: affine
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_HOST_AUTH_METHOD: trust

    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'affine', '-d', 'affine']
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  Affine:
    external: true

networks:
  traefik_default:
    external: true
    name: traefik_default
